### ISSUE TITLE
Python 3 version

### ISSUE THREAD

**Issue by pexnet** [allfro/pcappy#2]
Hi! 

I really like this library. Have you considered to create a python 3 compatible version?

BR

**Comment by allfro** [comment]
Hi @pexnet 

I've got a version 3 copy working here. Care to give it a test drive? If so, send me your email at ndouba.at.gmail.com to get the v3 copy.

**Comment by pexnet** [comment]
Hi,

I actually got an working v3 copy as well :). It wasn't that much that needed to be patched. I'm sorry for not letting you know. Would it be possible to create a v3 branch here and then I could compare.

**Comment by PidgeyL** [comment]
I am actually very interested in a Python3 version as well. @allfro, do you still have this? If so, care to share this? @pexnet, is your copy stable?

**Comment by allfro** [comment]
@PidgeyL sorry for the delayed response. I couldn't find the version I created. It should be fairly straight forward to port it though. I remember making a few changes that were related to file objects and print statements.

**Comment by allfro** [comment]
@pexnet and @PidgeyL: latest commit (98833ccf68a779fdfa97038037a74374a457f01d) adds support for Python 3. Let me know if you encounter any nasty bugs :)

**Comment by PidgeyL** [comment]
```
>>> import pcappy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pcappy-0.3-py3.4.egg/pcappy/__init__.py", line 9, in <module>
    from constants import *
ImportError: No module named 'constants'
>>> 
```

Is this normal? I installed it using easy_install3 pcappy

**Comment by allfro** [comment]
Please download it from GitHub.
